version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-22.9"

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Don't build any extra formats
formats: []
