#!/usr/bin/env python
# Copyright (c) 2015, Michael Boyle
# See LICENSE file for details: <https://github.com/moble/scri/blob/master/LICENSE>
"""
Creates a rh_FiniteRadii_CodeUnits.h5 file with fake GW strain data to run the
following tests in test_SpEC.py:
    * test_extrapolation
    * test_NRAR_extrapolation
    * test_file_io
"""

import os
from scri.sample_waveforms import create_fake_finite_radius_strain_h5file

if not os.getcwd().endswith("/tests"):
    raise OSError("Must be run in the directory $SCRI_HOME/tests/")

create_fake_finite_radius_strain_h5file(
    output_file_path = "../SpEC/samples/rh_FiniteRadii_CodeUnits.h5",
    ell_max = 3,
    t_1 = 2000.0,
)
