name: scri-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.7
  - scipy
  - matplotlib
  - h5py
  - numba>=0.49.1
  - quaternion>=2019.7.15.12.50.36
  - spinsfast
  - spherical_functions
  - sxs
  - sphinx>=3.1.0
  - sphinx_rtd_theme
  - numpydoc>=1.0.0
  - recommonmark>=0.6.0
